apiVersion: v1 
kind: ConfigMap 
metadata:
  name: shipping-config
  namespace: roboshop
data:
  CART_ENDPOINT: "cart-service:8080"
  DB_HOST: "mysql-service"

--- 

apiVersion: v1 
kind: Service 
metadata: 
  name: shipping-service
  namespace: roboshop 
spec: 
 selector: 
    tier: middle
    type: java
 ports: 
   - protocol: TCP 
     port: 8080 
     targetPort: 8080 


--- 


apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
spec:
 replicas: 1 
 selector: 
   matchLabels: 
      tier: middle 
      type: java
 template:
  metadata: 
    labels: 
      tier: middle 
      type: java
  spec: 
   containers: 
     - name: shipping
       image: devopshandson3/shipping:v1 
       ports: 
         - containerPort: 8080 
       envFrom: 
       - configMapRef: 
            name: shipping-config

   
    
       