apiVersion: v1 
kind: ConfigMap 
metadata:
  name: mysql-config
  namespace: roboshop
data:
  MYSQL_DATABASE: "cities"
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
--- 

apiVersion: v1 
kind: Secret
metadata:
 name: sql-creds 
 namespace: roboshop
type: opaque 
data:
 MYSQL_USER: c2hpcHBpbmc=
 MYSQL_PASSWORD: c2VjcmV0
 

--- 

apiVersion: v1 
kind: Service 
metadata: 
 name: mysql-service 
 namespace: roboshop
spec:
 selector: 
   tier: sql-db 
   type: mysql 
 ports: 
   - protocol: TCP 
     port: 3306
     targetPort: 3306

--- 

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    matchLabels:
      tier: sql-db 
      type: mysql # has to match .spec.template.metadata.labels
  serviceName: "mysql-service"
  replicas: 1 # by default is 1
  minReadySeconds: 3 # by default is 0
  template:
    metadata:
      labels:
        tier: sql-db 
        type: mysql # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql 
        image: devopshandson3/mysql:v1 
        ports:
        - containerPort: 3306
          name: sql-port
        envFrom:
          - configMapRef: 
             name: mysql-config
          - secretRef:
             name: sql-creds
        volumeMounts:
        - name: sqldb-volume
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: sqldb-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "dynamic-provis"
      resources:
        requests:
          storage: 1Gi

      

