apiVersion: v1 
kind: ConfigMap 
metadata:
  name: user-configs
  namespace: roboshop
data:
  REDIS_HOST: "redis"
  MONGO_URL: mongodb://mongo-service:27017/catalogue
  #adding
--- 
apiVersion: v1 
kind: Service 
metadata:
  name: user-service 
  namespace: roboshop
spec:
 selector:
    tier: login
    app: user
 ports:
   - protocol: TCP 
     port: 8080
     targetPort: 8080



--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
spec:
 replicas: 1 
 selector: 
   matchLabels: 
     tier: login
     app: user 
 template:
  metadata: 
    labels: 
     tier: login
     app: user
  spec: 
   containers: 
     - name: user
       image:  devopshandson3/user:v1
       ports: 
        - containerPort: 8080 
       envFrom:
       - configMapRef:
           name: user-configs 

  