apiVersion: v1 
kind: Service 
metadata:
 name: redis
 namespace: roboshop
spec:
 selector:
   tier: cacheing-service
   app: redis 
 ports: 
  - protocol: TCP 
    port: 6379
    targetPort: 6379
 clusterIP: None

--- 


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis 
  namespace: roboshop
spec:
  selector:
    matchLabels:
      tier: cacheing-service 
      app: redis # has to match .spec.template.metadata.labels
  serviceName: "redis"
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        tier: cacheing-service 
        app: redis # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
          name: redis-port
        volumeMounts:
        - name: redis-volume
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "dynamic-provis"
      resources:
        requests:
          storage: 1Gi